project 'DebatesApp.xcodeproj'

platform :ios, '10.0'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DebatesApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DebatesApp
  
  pod 'Alamofire', '~> 4.0'

end
